---
name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - preprodseb

jobs:
  test:
    runs-on: preprod

    steps:
      - run: echo $MSG
        env:
          MSG: ${{ vars.MSG }}
      - run: |
          echo "Chut ne le répétez pas : $SECURE_MSG" > /var/www/html/secure.txt
        env:
          SECURE_MSG: ${{ secrets.SECURE_MSG }}
      - run: cat /var/www/html/secure.txt 