---
name: preprod release

on:
  push:
    branches:
      - preprodseb

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name : test env and deploy a sample html file
        run: |
          ls -alh
          whoami
          cp index.html /var/www/html/