---
name: preprod release

on:
  push:
    branches:
      - preprodseb

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: ls -alh
      - run: whoami
      - run: cp index.html /var/www/html/